version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_server_cream
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventory_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - cream_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cream
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - cream_network

  web:
    build: .
    container_name: web_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html     # 👈 ให้ root อยู่ที่โฟลเดอร์เดียวกับ compose
    depends_on:
      - db
    networks:
      - cream_network

networks:
  cream_network:
    driver: bridge
